config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about" , as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :books, only: [:create, :index, :show, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :users, only: [:show, :edit,:create,:index,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
	
	has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  validates_uniqueness_of :book_id, scope: :user_id
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, except:[:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_user
      flash[:notice] = "Sign in successfully."
      user_path(resource)  #指定したいパスに変更
    else
      flash[:notice] = "Sign up successfully."
      user_path(resource) #指定したいパスに変更
    end
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end


  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :name, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    if comment.save
      redirect_to book_path(book)
    else
      @error_comment = comment
      @book_comment = BookComment.new
      @book = Book.find(params[:id])
      @new_book = Book.new
      @user = @book.user
      render 'books/show'
    end
  end

  def destroy
    BookComment.find_by(book_id: params[:book_id], id: params[:id]).destroy
    redirect_back(fallback_location:root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  
  def index
  	@books = Book.all
    @book = Book.new
    @user = current_user
  end
  
  
  def show
  	@book = Book.find(params[:id])
  	@user = @book.user
  	@newbook = Book.new
  	@book_comment = BookComment.new
  end
  
  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
    @user = User.find(current_user.id)
    if @book.save
      flash[:notice] = "You have creatad book successfully."
  	  redirect_to book_path(@book.id)
    else
      @books = Book.all
      flash[:notice] = "error"
      render :index
    end
  end
  
  def edit
    @book = Book.new
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      flash[:notice] = "error"
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location:root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location:root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @users = User.all
    if @user.update(user_params)
       redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

private
  def user_params
     params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(65,65) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
        <th>name</th>
        <th><%= user.name %></th>
    </tr>
    <tr>
        <th>introduction</th>
        <th><%= user.introduction%></th>
    </tr>
  </tbody>
</table>

<div class="row">
  <%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/books/_list.html.erb
<h1 class="my -3">New book</h1>
<%= form_with model: book, url: books_path, method: :post do |f| %>

<% if book.errors.any? %>
    <div id="error_explanation" >
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <%= book.errors.full_messages.each do |message|%>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class:"form-control book_title"%>
</div>
<div class="form-group">
  <%= f.label :opinion %>
  <%= f.text_area :body, class: "form-control book_body"%>
</div>
<div class="form-group">
  <%= f.submit "Create Book", class: "btn btn-success" %>
</div>

<% end %>

app/views/books/edit.html.erb
<div class="container">

	

	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<h1>Editing Book</h1>

			<%= form_with model:@book, url: book_path(@book), method: :patch do |f| %>
				<h4>Title</h4>
				<%= f.text_field :title %>
				<h4>Opinion</h4>
				<%= f.text_area :body %>
				<%= f.submit "Update Book" %>
			<% end %>
			<%= link_to "Show", book_path(@book.id) %>
			|
			<%= link_to "Back", books_path %>

		</div>
	</div>
</div>

app/views/books/index.html.erb
	<div class=container>


		<% if @book.errors.any? %>
			 <div id="error_explanation" class="alert alert-danger">
				<ul>
				    <% @book.errors.full_messages.each do |message| %>
				    <li><%= message %></li>
				    <% end %>
				</ul>
			</div>
		<% end %>


		<div class=row>
			<div class="col-md-3">
				<%= render "books/info", user: @user%>
			

				<%= render "books/list", book: @book %>
			</div>

			<div class="col-md-8 offset-md-1">
				<h2>Books</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |book| %>
							<tr>
								<td>
									<%= link_to user_path(book.user_id) do %>
									  <%= image_tag book.user.get_profile_image(100,100) %>
									<% end %>
								</td>
								<td>
									<%= link_to book_path(book.id) do %>
										<%= book.title %>
									<% end %>
								<td>
	                <% if book.favorited_by?(current_user) %>
	                  <%= link_to book_favorites_path(book_id: book.id),class: "like" ,method: :delete do %>
	                    <i class="fas fa-heart like"></i><%= book.favorites.count%>
	                  <% end %>
	                <% else %>
	                  <%= link_to book_favorites_path(book_id: book.id), method: :post do %>
	                    <i class="fas fa-heart unlike"></i><%= book.favorites.count %>
	                  <% end %>
	                <% end %>
                </td>
                <td></td>
								</td>
								<td><%= book.body %></td>
								<td><p>コメント数：<%= book.book_comments.count %></p></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

app/views/books/new.html.erb
<%= form_with model:@book do |f| %>
	<label for="title">Title</label><br>
	<%= f.text_field :title, id:"title" %><br>
	<label for="opinion">Opinion</label><br>
	<%= f.text_area :body, id:"opinion" %><br>
	<%= f.submit "Create Book" %>
<% end %>

<footer>
    <div class="container">
    	<div class="row">
    		<div class="col-xs-3 col-xs-offset-9">
    			<p>CopyRight Infratop.inc</p>
    		</div>
        </div>
    </div>
</footer>

app/views/books/show.html.erb
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<%= render "books/info", user:@user%>
				<%= render "books/list", book: @newbook %>
			</div>
			<div class="col-md-8 offset-md-1">
				<h2>Book detail</h2>
				<table class="table table-hover table-inverse">
					<tbody>
						<tr>
							<td>
								<%= link_to user_path(@book.user_id) do %>
									<%= image_tag @book.user.get_profile_image(100,100) %><br>
									<%= @book.user.name %>
								<% end %>
							</td>


							<td>
								<%= link_to book_path(@book.id) do %>
									<%= @book.title %>
								<% end %>
							</td>
							<td><%= @book.body %></td>
							<% if @book.user == current_user %>
								<td><%= link_to "Edit", edit_book_path, class: "btn-sm btn-success" %></td>
								<td><%= link_to "Destroy", book_path(@book.id), method: :delete,class: "btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %></td>
							<% end %>

							<td>
                  <% if @book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(book_id: @book.id),class: "like" ,method: :delete do %>
                      <i class="fas fa-heart like"></i><%= @book.favorites.count%>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(book_id: @book.id), method: :post do %>
                      <i class="fas fa-heart unlike"></i><%= @book.favorites.count %>
                    <% end %>
                  <% end %>
              </td>
              <td><p>コメント数：<%= @book.book_comments.count %></p></td>
							</tr>
					</tbody>
				</table>
				<div>
				  
				  <% @book.book_comments.each do |book_comment| %>
				    <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
				    <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
				    <%= book_comment.comment %>
				    <% if book_comment.user == current_user %>
				    	<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete,class: "btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
				    <% end %>
				  <% end %>
				</div>
				<div>
				  <%= form_with model: [@book, @book_comment] do |f| %>
				    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
				    <%= f.submit "送信" %>
				  <% end %>
				</div>
			</div>
		</div>
	</div>

	<footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <div class = "row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
    	Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>
      </h1>
      <body>
      <p class="text-center">CopyRight Infratop.inc</p>
    </body>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>

<% end %>

<div class="container">
  <div class = "row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
    	Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>
      </h1>
      <p>
    	In<i class="fas fa-book"></i><strong>Bookers</strong><br>
    	you can share and exchange your opinions , inpressions , and emotions<br>
    	about various books!
      </p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
           <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>





      <p class="text-center">CopyRight Infratop.inc</p>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id),class:"nav-link text-light" do%>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path ,class:"nav-link text-light" do%>
                    <i class="fas fa-users"></i>Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path ,class:"nav-link text-light" do %>
                    <i class="fas fa-book-open"></i>Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete ,class:"nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i>Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path,class:"nav-link text-light" do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path,class:"nav-link text-light" do %>
                    <i class="fas fa-link"></i>About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path,class:"nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path,class:"nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i>Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
    <% end %>
  <main>
      <%= yield %>
  </main>


</body>
</html>

app/views/users/edit.html.erb
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <div id="error_explanation">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <label for="inputName">Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name",class:"form-control name"%>
          </div>

          <div class="form-group">
            <label for="user_name">Image</label>
            <%= f.file_field :profile_image, accept: "image/*" %>
          </div>


          <div class="form-group">
            <label for="inputIntroduction">Introduction</label>
            <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction",class:"form-control introduction"%>
          </div>

          <div class="form-group">
            <%= f.submit "Update User",class:"btn btn-secondary"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div id="error_explanation">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <%= render "books/info",user:@user%>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title ,class:"form-control book_title"%>
          </div>
          <div class="form-group">
            <label for="book_body">Opinion</label>
            <%= f.text_area :body,class:"form-control book_body"%>
          </div>
            <div class="form-group">
            <%= f.submit 'Create Book' ,class:"btn btn-success"%>
          </div>
        <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user|%>
                <tr>
                    <td>
                        <%= link_to user_path(user) do %>
                            <%= image_tag user.get_profile_image(40,48) %>
                        <%end%>
                    </td>
                    <td>
                        <%= user.name %>
                    </td>
                    <td>
                        <%= link_to "Show", user_path(user) %>
                    </td>


                    </td>
                </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container">
<div class="row">
<body>
<div class="col-md-3">
<%= render 'books/info', user: @user %>
<%= render 'books/list', book: @book %>
</div>



<div class="col-md-8 offset-md-1">
<h1>Books</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion </th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
          <%= image_tag book.user.get_profile_image(40,48) %>
        <%end%>
      </td>
      <td>
        <%= link_to book.title ,book_path(book)%>
      </td>
      <td>
        <%= book.body%>
      </td>
      
			<td>
          <% if book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(book_id: book.id),class: "like" ,method: :delete do %>
              <i class="fas fa-heart like"></i><%= book.favorites.count%>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(book_id: book.id), method: :post do %>
              <i class="fas fa-heart unlike"></i><%= book.favorites.count %>
            <% end %>
          <% end %>
      </td>
      <td><p>コメント数：<%= book.book_comments.count %></p></td>
  </tr>
  <% end %>
</tbody>
</table>
<p class="text-center">CopyRight Infratop.inc</p>
</div>
</body>
</div>
</div>